### ISSUE TITLE
feat(patch): Malfunction of video seek by swiping

### ISSUE THREAD

**Issue by tesmite** [d4n3436/revanced-patches-android5#14]
### Application

YouTube ReVanced

### Issue

It is possible to seek videos by swiping the video screen, but unlike recent versions, it is possible to respond to a horizontal swipe without a long press, which may result in a false response.

https://github.com/d4n3436/revanced-patches-android5/assets/111569199/64906954-3813-434c-8adc-c7796795a3fd

### Patch

Option to disable video seek by swiping the video screen, or to make it responsive only on long presses.

### Motivation

This malfunction can be stressful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by eldepor** [comment]
I can confirm that with 5th/8th November "release" (v2.161.1 & 0.96.9) I'm not having this issue.

**Comment by tesmite** [comment]
I checked again in my device and found that the layout information is not optimized correctly when the app is updated with the "spoof app version" option set to 16.03.35.
I apologize for the lack of research.
