### ISSUE TITLE
bug: default-video-quality not working properly with old version spoof

### ISSUE THREAD

**Issue by tesmite** [d4n3436/revanced-patches-android5#15]
### Type

Other

### Bug description

When changing the video quality with the "Enable save video quality" option activated, the quality selected does not match the quality set as default, making it unusable under the environment of the old version's image quality selection UI

### Steps to reproduce

Step 1. spoof app version to old version like 16.03.35
Step 2. Enable "Enable save video quality" option
Step 3. Play the video and change the video quality from the options

### Screenshots or videos

https://github.com/d4n3436/revanced-patches-android5/assets/111569199/947654b8-b084-4a98-b847-305c713a75f2

### Device Environment

Android 12, AQUOS R5G
Android 5.0, HTC butterfly 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tesmite** [comment]
This bug, like the other patch request, was caused by a spoof to an older version, so the text has been changed.
This bug did not occur in ReVanced Extended by inotia00 for Android Oreo or later, but it did occur in ReVanced Extended by kitadai31 for Android 6-7.

**Comment by d4n3436** [comment]
> This bug did not occur in ReVanced Extended by inotia00 for Android Oreo or later, but it did occur in ReVanced Extended by kitadai31 for Android 6-7.

In that case you should open an issue on the [RVX for Android 6-7 repo](https://github.com/kitadai31/revanced-patches-android6-7/issues) since the code of this repo is based on it.
