### ISSUE TITLE
bug: watched videos don't get saved in history

### ISSUE THREAD

**Issue by jpa102** [d4n3436/revanced-patches-android5#18]
### Type

Error at runtime

### Bug description

old layout now works (after feb 29, at least for me) but whenever i play any long-form video from start to finish, it doesn't get counted as "watched" in the history tab. only videos from shorts get saved

### Steps to reproduce

turn off spoof player parameter, then watch any video and check the history.

turn back on the setting, repeat and check

### Additional context

edit: the latest revanced made the watch history functional again

### Device Environment

android 5, oppo a37fw

android 13, galaxy m12, non root

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
Fixed in e428f7a
