### ISSUE TITLE
bug: App Crash

### ISSUE THREAD

**Issue by AsphaltKoreaWiki** [d4n3436/revanced-patches-android5#28]
### Type

Other

### Bug description

I'm going to install and run a pre-patched app, but the app crashes after the logo appears. 

### Steps to reproduce

1. Install the app. 
2. You run the app. 

### Device Environment

Android 5.0.2 Rooted, Galaxy Tab 4 10.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jpa102** [comment]
> 1. Install the app.
> 2. You run the app.

where did you get that pre-patched youtube apk from? specify a source

installing pre-patched apks is not recommended, at least that's what the official revanced devs say

do you have the [microG](https://www.github.com/ReVanced/GmsCore) app installed?

**Comment by AsphaltKoreaWiki** [comment]
I installed the microG, and it worked.
