### ISSUE TITLE
bug: Youtube pushed another "force update" client app version

### ISSUE THREAD

**Issue by eldepor** [d4n3436/revanced-patches-android5#6]
### Type

Other

### Bug description

Cant use the app because its says its obsolete

"Switch to YouTube.com 
This version of YouTube is outdated and no updates are available for your device. Open YouTube.com in your browser. "
### Steps to reproduce

Just open the app itself

### Screenshots or videos

![image](https://github.com/d4n3436/revanced-patches-android5/assets/19383172/19baa2db-0c9c-488f-81bd-074993b87b79)

### Device Environment

Android 5.0.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
Huh, I thought ReVanced already included a patch for this.
A temporary solution is to clear cache and app data.

**Comment by eldepor** [comment]
YouTube has been doing things and updating stuff recently if I'm not wrong, maybe that broke the code or something idk. RV still working on newer androids tho.

**Comment by d4n3436** [comment]
I've added a new patch (`disable-update-screen`) that fixes the issue. Repatch YouTube with the updated commands.
If any bug appears when opening the app, reinstall YouTube and MicroG.

**Comment by eldepor** [comment]
Nice. I think you forgot to upload the patches .jar file. And to update the command with the new version number.

**Comment by eldepor** [comment]
Nice thanks. But no new jar file for 2.160.9? Or I'm missing something?

**Comment by d4n3436** [comment]
I know, it takes some time to build the jar file so I released the new version before uploading the file.

**Comment by eldepor** [comment]
So far it's working great and screen dissapreaed. Thanks!
